# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_auto_20170909_0107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
